name: CI

on:
  push:
    branches:
      - main
      - ci

jobs:
  build-with-macos:
    name: Build with macOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ldid
        uses: MOZGIII/install-ldid-action@master
        with:
          tag: v2.1.5-procursus7

      - name: build
        run: make TARGET=ios

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: output/ios
